---
name: super-linter

on:
  workflow_dispatch:

  workflow_call:

  push:

  pull_request:

# Don't grant any access by default
permissions: {}

env:
  target_ref: ${{ github.head_ref || github.ref_name }}
  GO111MODULE: on
  GOPRIVATE: ''

jobs:
  super-linter:
    name: Super-Linter
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    ############################################
    # Grant status permission for MULTI_STATUS #
    ############################################
    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: actions/checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.target_ref }}
          token: ${{ github.token }}
          fetch-depth: 0

      - name: super-linter/super-linter
        uses: super-linter/super-linter@latest
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ github.token }}
          LOG_LEVEL: VERBOSE
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_EDITORCONFIG: false
          VALIDATE_GITHUB_ACTIONS: false
